# Generated by Django 3.1.5 on 2021-01-18 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='started',
            name='tfnew_value',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='started',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
