# Generated by Django 3.1.5 on 2021-01-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_auto_20210118_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='started',
            old_name='tfnew_value',
            new_name='stfnew_value',
        ),
        migrations.AddField(
            model_name='cancelled',
            name='catfnew_value',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='cotfnew_value',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='proceeding',
            name='ptfnew_value',
            field=models.BooleanField(null=True),
        ),
    ]
